import "reflect-metadata";
import { generateInternalServerErrorResponse, LoggerServiceInterface } from "@yac/util";
import { APIGatewayProxyEventV2, APIGatewayProxyStructuredResultV2 } from "aws-lambda";
import { container } from "../inversion-of-control/container";
import { TYPES } from "../inversion-of-control/types";
import { UserControllerInterface } from "../controllers/user.controller";

const userController = container.get<UserControllerInterface>(TYPES.UserControllerInterface);
const loggerService = container.get<LoggerServiceInterface>(TYPES.LoggerServiceInterface);

export const handler = async (event: APIGatewayProxyEventV2): Promise<APIGatewayProxyStructuredResultV2> => {
  try {
    loggerService.trace("getUsersByGroupId called", { event }, "getUsersByGroupId handler");

    const response = await userController.getUsersByGroupId(event);

    return response;
  } catch (error: unknown) {
    // We should never get here, as Controller classes should never throw, but if for some reason we do, we need to log it
    loggerService.error("Catastrophic error in getUsersByGroupId handler", { error, event }, "getUsersByGroupId handler");

    return generateInternalServerErrorResponse(error);
  }
};
